### ISSUE TITLE
Building master on Debian bullseye fails with compiler error

### ISSUE THREAD

**Issue by bradfordboyle** [greenplum-db/gpdb#10953]
### Greenplum version or build

greenplum-db/gpdb: master eea8f0702a

### OS version and uname -a

```console
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux bullseye/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux f330ff945822 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux
```

Docker Image `debian@sha256:608ee7989e7248c50c3b74eb68481f92205c8b54704eb1200d370bb3ca1a4425`

### autoconf options used ( config.status --config )

```console
$ ./config.status --config
'--with-python' '--with-libxml' '--disable-gpcloud' '--disable-orca'
```

### Installation information ( pg_config )

_N/A_

### Expected behavior

Building completes successfully.

### Actual behavior

Building fails with

```console
$ gcc -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3 -Wno-format-truncation -Wno-stringop-truncation -O3  -Werror=uninitialized -Werror=implicit-function-declaration -I../../../src/interfaces/libpq -I../../../src/include  -D_GNU_SOURCE -I/usr/include/libxml2   -c -o cdbdtxrecovery.o cdbdtxrecovery.c

Unable to coalesce ssa_names 11 and 12 which are marked as MUST COALESCE.
htab_11(ab) and  htab_12(ab)
during RTL pass: expand
cdbdtxrecovery.c: In function 'gatherRMInDoubtTransactions':
cdbdtxrecovery.c:287:1: internal compiler error: SSA corruption
  287 | gatherRMInDoubtTransactions(int prepared_seconds, bool raiseError)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-10/README.Bugs> for instructions.
```

### Step to reproduce the behavior

Launch a container with

```sh
docker run -it --rm -v $PWD:/tmp/build/gpdb -w /tmp/build/gpdb debian@sha256:608ee7989e7248c50c3b74eb68481f92205c8b54704eb1200d370bb3ca1a4425 bash
```

Inside the container, install require build dependencies:

```sh
apt-get update -q=1
apt-get install -y -q=1 \
    bison \
    flex \
    g++ \
    gcc \
    libapr1-dev \
    libbz2-dev \
    libcurl4-openssl-dev \
    libevent-dev\
    libfile-dircompare-perl \
    libpython3-dev \
    libreadline-dev \
    libxerces-c-dev \
    libxml2-dev \
    libzstd-dev \
    make \
    python3 \
    python3-distutils \
    zlib1g-dev
```

Building Greenplum with

```sh
./configure --with-python --with-libxml --disable-gpcloud --disable-orca
make -j
```

**Comment by d** [comment]
@bradfordboyle thank you for reporting this issue. I've managed to repro this. Here's a minimized repro (from the original):

```c
a() {
  int b;
  __sigsetjmp();
  for (;;) {
    if (b)
      b = c();
    d();
  }
}
```

Running a simple `gcc -O3 -c rofl.c` would trigger the same GCC crash:
```
Unable to coalesce ssa_names 2 and 4 which are marked as MUST COALESCE.
b_2(ab) and  b_4(ab)
during RTL pass: expand
cdbdtxrecovery.i:1:1: internal compiler error: SSA corruption
    1 | a() {
      | ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.

```

**Comment by hlinnaka** [comment]
Cool, short repro for a compiler bug!

Looks similar to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96349. However, the repro from that bug doesn't error out when I try it on the docker shell, so I think it should've been fixed in that version. So maybe this is a different but similar bug?

Want to do the honors and submit a bug report to GCC?

**Comment by bradfordboyle** [comment]
@d Using the minimized repro you posted does not reproduced on Debian bullseye

```console
$ gcc --version
gcc (Debian 10.2.0-13) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

but I still see the failure when trying to compile GPDB. The repro _does_ produce the failure on Ubuntu 20.04.

**Comment by d** [comment]
> @d Using the minimized repro you posted does not reproduced on Debian bullseye
> 
> ```console
> $ gcc --version
> gcc (Debian 10.2.0-13) 10.2.0
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```
> 
> but I still see the failure when trying to compile GPDB. The repro _does_ produce the failure on Ubuntu 20.04.

I posted a second repro on Launchpad (for gcc-10 and gcc-snapshot in Ubuntu "groovy"):

```
a;
b() {
  int c, d;
  __sigsetjmp();
  for (; a;)
    for (; d;) {
      if (c)
        c = e();
      f();
    }
}
```

Wonder if that works (to err) for you two

**Comment by d** [comment]
Seems my second repro activates the bug everywhere... Anyway I reported it to [launchpad](https://bugs.launchpad.net/ubuntu/+source/gcc-10/+bug/1899114). I'm under the impression they will upstream the fix (and the bug).

**Comment by bradfordboyle** [comment]
It looks like a new version of gcc-10 has been published in the Debian archive. Using 10.2.1-1 I am able to build the referenced commit (https://github.com/greenplum-db/gpdb/commit/eea8f0702a3aaebda30e288d1cd22d2c69823723).
