### ISSUE TITLE
postgres fdw on greenplum7 Alpha:libpq is incorrectly linked to backend functions

### ISSUE THREAD

**Issue by geostar123** [greenplum-db/gpdb#11400]
### Greenplum version or build
PostgreSQL 12beta2 (Greenplum Database 7.0.0-alpha.0+dev.14163.g327f60a build dev) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5), 64-bit compiled

### OS version and uname -a
Linux pgdb-master 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Installation information ( pg_config )
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--with-gssapi' '--pre                                                                                                             fix=/usr/local/gpdb'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/include/libxml2
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Werror=vla -Wendif-labels -                                                                                                             Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexces                                                                                                             s-precision=standard -Wno-unused-but-set-variable -Werror=implicit-fallthrough=3                                                                                                              -Wno-format-truncation -O3  -Werror=uninitialized -Werror=implicit-function-dec                                                                                                             laration
CFLAGS_SL = -fPIC
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags
LDFLAGS_EX =
LDFLAGS_SL =
LIBS = -lpgcommon -lpgport -lpthread -lxerces-c -lbz2 -lxml2 -lrt -lgssapi_krb5                                                                                                              -lzstd -lz -lreadline -lrt -lcrypt -ldl -lm  -lcurl
VERSION = PostgreSQL 12beta2

### Expected behavior
  I can query foreign table with postgres fdw on greenplum7.
 
### Actual behavior

psql: ERROR:  could not connect to server "postgres_svr"
DETAIL:  libpq is incorrectly linked to backend functions
### Step to reproduce the behavior
Postgresql 11.6 Physical Table:
 create table m9_x86(id int,s smallint,c text,l bigint,f numeric(12,2), d double precision,t date,ts1 timestamp with time zone,ts2 timestamp without time zone,g GEOMETRY,PRIMARY KEY(id));
 CREATE INDEX m9_x86_gix ON m9_x86 USING GIST (g);

Step 1:
  //Postgresql 11.6 server is installed on host fdw8-laptop-pc,and now it  started.
   psql>CREATE SERVER postgres_svr FOREIGN DATA WRAPPER postgres_fdw OPTIONS(host 'fdw8-laptop-pc', port '5432', dbname 'postgres');
Step 2:
   psql>CREATE USER MAPPING FOR gpadmin SERVER postgres_svr OPTIONS(user 'test', password '1');
Step 3:
   //On host fdw8-laptop-pc,there is one spatial table named m9_x86 metioned above 
   psql>CREATE FOREIGN TABLE m9_x86_pg11(id int,s smallint,c text,l bigint,f numeric(38,15), d double precision,t date,ts1 timestamp with time zone,ts2 timestamp without time zone,g GEOMETRY) SERVER postgres_svr OPTIONS (table_name 'm9_x86');

Step 4:
   psql>select * from m9_x86_pg11;
   
errors occured:
psql: ERROR:  could not connect to server "postgres_svr"
DETAIL:  libpq is incorrectly linked to backend functions

Why?Thanks.

**Comment by geostar123** [comment]
I fixed this issue with editing Makefile and postgres_fdw.h as following:
Makefile:
# contrib/postgres_fdw/Makefile

MODULE_big = postgres_fdw
OBJS = postgres_fdw.o option.o deparse.o connection.o shippable.o $(WIN32RES)
PGFILEDESC = "postgres_fdw - foreign data wrapper for PostgreSQL"

PG_CPPFLAGS = -I$(libpq_srcdir)

SHLIB_LINK_INTERNAL = $(libpq)
#SHLIB_LINK_INTERNAL = -Wl,--exclude-libs=libpq.a -Wl,-Bstatic $(libpq) -Wl,-Bdynamic

EXTENSION = postgres_fdw
DATA = postgres_fdw--1.0.sql

REGRESS = postgres_fdw gp_postgres_fdw

ifdef USE_PGXS
PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)
else
SHLIB_PREREQS = submake-libpq
subdir = contrib/postgres_fdw
top_builddir = ../..
include $(top_builddir)/src/Makefile.global
include $(top_srcdir)/contrib/contrib-global.mk
endif

postgres_fdw.h

/*-------------------------------------------------------------------------
 *
 * postgres_fdw.h
 *		  Foreign-data wrapper for remote PostgreSQL servers
 *
 * Portions Copyright (c) 2012-2019, PostgreSQL Global Development Group
 *
 * IDENTIFICATION
 *		  contrib/postgres_fdw/postgres_fdw.h
 *
 *-------------------------------------------------------------------------
 */
#ifndef POSTGRES_FDW_H
#define POSTGRES_FDW_H

#include "foreign/foreign.h"
#include "lib/stringinfo.h"
#include "nodes/pathnodes.h"
#include "utils/relcache.h"

/* postgres_fdw is compiled as a backend, it needs the server's
 * header files such as executor/tuptable.h. It also needs libpq
 * to connect to a remote postgres database, so it's statically
 * linked to libpq.a which is compiled as a frontend using
 * -DFRONTEND.
 *
 * But the struct PQconninfoOption's length is different between
 * backend and frontend, there is no "connofs" field in frontend.
 * When postgres_fdw calls the function "PQconndefaults" implemented
 * in libpq.a and uses the returned PQconninfoOption variable, it crashs,
 * because the PQconninfoOption variable returned by libpq.a doesn't contain
 * the "connofs" value, but the postgres_fdw thinks it has, so it crashes.
 *
 * We define FRONTEND here to include frontend libpq header files.
 */

#include "libpq-fe.h"


//#ifdef LIBPQ_FE_H
//#error "postgres_fdw.h" must be included before "libpq-fe.h"
//#endif /* LIBPQ_FE_H */

//#ifndef FRONTEND
//#define FRONTEND
//#include "libpq-fe.h"
//#undef FRONTEND
//#else
//#include "libpq-fe.h"
//#endif /* FRONTEND */


......
Now I succeeded to  query foreign table.But,there is another error occured while executing aggregation operation as following:
select avg(l) from m9_x86_pg11 where id < 100 group by id;

 psql: ERROR:  path of type 46 is missing distribution locus (pathnode.c:472)

**Comment by lij55** [comment]
The link issue is fixed by this commit: https://github.com/greenplum-db/gpdb/commit/667f0c37bc6d7bce7be8b758652ef95ddb823e19

**Comment by adam8157** [comment]
The issue still exists, discussed this with @lij55 offline, re-open.
