### ISSUE TITLE
Conflagration error occur even all dependencies installed 

### ISSUE THREAD

**Issue by Dishcreate** [greenplum-db/gpdb#3965]
### Step to reproduce the behavior

./configure: line 12305: #include: command not found
checking how to run the C++ preprocessor... g++ -std=c++11 -E
checking gpos/_api.h usability... no
checking gpos/_api.h presence... no
checking for gpos/_api.h... no

**Comment by danielgustafsson** [comment]
This was addressed in PR #2659 but for some strange reason it had fallout errors that haven't been investigated yet.

**Comment by d** [comment]
@Dishcreate How can we reproduce your error?

**Comment by Dishcreate** [comment]
Hi... I have follow instruction in PR #2659 by editing configure.in file as you propose. But still getting same error as previously.

**Comment by danielgustafsson** [comment]
I updated the PR over the weekend, the patch in #2659 fixes it for me. If you edit configure.in manually, make sure you run `autoconf` afterwards to rebuild the `configure` program.

**Comment by Dishcreate** [comment]
Thank you it was work for me also

**Comment by danielgustafsson** [comment]
> On 27 Nov 2017, at 08:41, DInusha DIlanka <notifications@github.com> wrote:
> 
> Thank you it was work for me also

Perfect, thanks for confirming! I’ve force-pushed the branch again to get the PR built to see if the test is flaky or consistently fails on this.

**Comment by Dishcreate** [comment]
Hi.. I end up with another when i configure as follow. I have installed gporca sucessfully and tested it, but error still there.
checking gpos/_api.h usability... no
checking gpos/_api.h presence... no
checking for gpos/_api.h... no
configure: error: GPOS header files are required for Pivotal Query Optimizer (orca)

**Comment by danielgustafsson** [comment]
> On 29 Nov 2017, at 07:58, DInusha DIlanka <notifications@github.com> wrote:
> 
> Hi.. I end up with another when i configure as follow. I have installed gporca sucessfully and tested it, but error still there.
> checking gpos/_api.h usability... no
> checking gpos/_api.h presence... no
> checking for gpos/_api.h... no
> configure: error: GPOS header files are required for Pivotal Query Optimizer (orca)

Did you install the ORCA headers/libraries in the normal system location or with a prefix? If you used a non-standard location you need to use --with-includes=/path/to/headers and --with-libraries/path/to/libs to help autoconf finding them.

**Comment by Dishcreate** [comment]
Hi @danielgustafsson 
I used as bellow 
./configure --with-perl --with-python --with-libxml --with-gssapi -with-includes=/usr/local/include --with-libraries=/usr/local/lib --prefix=/usr/local/gpdb

Then I end up with error as bellow
checking for gpdbcost/CCostModelGPDB.h... no
configure: error: GPDB Cost Model header files are required for Pivotal Query Optimizer (orca)

**Comment by danielgustafsson** [comment]
> On 29 Nov 2017, at 09:43, DInusha DIlanka <notifications@github.com> wrote:
> 
> Hi @danielgustafsson
> I used as bellow
> ./configure --with-perl --with-python --with-libxml --with-gssapi -with-includes=/usr/local/include --with-libraries=/usr/local/lib --prefix=/usr/local/gpdb
> 
> Then I end up with error as bellow
> checking for gpdbcost/CCostModelGPDB.h... no
> configure: error: GPDB Cost Model header files are required for Pivotal Query Optimizer (orca)

And how did you install ORCA and to where?

**Comment by Dishcreate** [comment]
I follow instruction from here
https://github.com/greenplum-db/gporca

**Comment by Dishcreate** [comment]
Hi... How can i fix this error 
checking Checking ORCA version... configure: error: Your ORCA version is expected to be 2.50.XXX
