### ISSUE TITLE
resource queue query counts inaccurate after querying pg_stat table

### ISSUE THREAD

**Issue by skahler-vmware** [greenplum-db/gpdb#4582]
### Greenplum version or build

```
gpadmin=# select version();
                                                                                                       version
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.5devel (Greenplum Database 6.0.0-alpha.0+dev.3785.g3969635 build dev-oss) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit compiled on Feb 23 2018 16:15:18
(1 row)
```

### OS version and uname -a

```
[gpadmin@ip-172-31-6-188 pg_log]$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[gpadmin@ip-172-31-6-188 pg_log]$ uname -a
Linux ip-172-31-6-188.ec2.internal 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[gpadmin@ip-172-31-6-188 pg_log]$
```

### autoconf options used ( config.status --config )

```
[gpadmin@ip-172-31-6-188 gpdb]$ ./config.status --config
'--with-perl' '--with-python' '--with-libxml' '--disable-orca' '--with-gssapi' '--prefix=/usr/local/gpdb' 'CFLAGS=-I/usr/local/gpdb/include/ -L/usr/local/gpdb/lib/'
```

### Installation information ( pg_config )

```
[gpadmin@ip-172-31-6-188 gpdb]$ pg_config
BINDIR = /usr/local/gpdb/bin
DOCDIR = /usr/local/gpdb/share/doc/postgresql
HTMLDIR = /usr/local/gpdb/share/doc/postgresql
INCLUDEDIR = /usr/local/gpdb/include
PKGINCLUDEDIR = /usr/local/gpdb/include/postgresql
INCLUDEDIR-SERVER = /usr/local/gpdb/include/postgresql/server
LIBDIR = /usr/local/gpdb/lib
PKGLIBDIR = /usr/local/gpdb/lib/postgresql
LOCALEDIR = /usr/local/gpdb/share/locale
MANDIR = /usr/local/gpdb/share/man
SHAREDIR = /usr/local/gpdb/share/postgresql
SYSCONFDIR = /usr/local/gpdb/etc/postgresql
PGXS = /usr/local/gpdb/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE = '--with-perl' '--with-python' '--with-libxml' '--disable-orca' '--with-gssapi' '--prefix=/usr/local/gpdb' 'CFLAGS=-I/usr/local/gpdb/include/ -L/usr/local/gpdb/lib/'
CC = gcc
CPPFLAGS = -D_GNU_SOURCE -I/usr/local/gpdb/include
CFLAGS = -L/usr/local/gpdb/lib/ -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -fno-aggressive-loop-optimizations -Wno-unused-but-set-variable -Wno-address -Werror=uninitialized -I/usr/local/gpdb/include
CFLAGS_SL = -fpic
LDFLAGS = -Wl,--as-needed -Wl,-rpath,'/usr/local/gpdb/lib',--enable-new-dtags -L/usr/local/gpdb/lib
LDFLAGS_SL =
LIBS = -lpgport -lxml2 -lrt -lgssapi_krb5 -lcrypt -ldl -lm -L/usr/local/gpdb/lib
VERSION = PostgreSQL 8.5devel
```

### Expected behavior

Queries count available after querying pg_stat tables

### Actual behavior

Query numbers do not update

### Step to reproduce the behavior

```
[gpadmin@ip-172-31-6-188 ~]$ psql -e -f test.sql
set stats_queue_level=on;
SET
create resource queue q with (active_statements = 10);
CREATE QUEUE
create user resqueuetest with resource queue q;
CREATE ROLE
set role resqueuetest;
SET
select 1;
 ?column?
----------
        1
(1 row)

select 1;
 ?column?
----------
        1
(1 row)

select 1;
 ?column?
----------
        1
(1 row)

select * from pg_stat_resqueues;
 queueid | queuename  | n_queries_exec | n_queries_wait | elapsed_exec | elapsed_wait
---------+------------+----------------+----------------+--------------+--------------
    6055 | pg_default |              0 |              0 |            0 |            0
   23340 | q          |              3 |              0 |            0 |            0
(2 rows)

reset role;
RESET
drop role resqueuetest;
DROP ROLE
drop resource queue q;
DROP QUEUE
SELECT * FROM pg_stat_bgwriter;
 checkpoints_timed | checkpoints_req | buffers_checkpoint | buffers_clean | maxwritten_clean | buffers_backend | buffers_alloc
-------------------+-----------------+--------------------+---------------+------------------+-----------------+---------------
                62 |              26 |               1233 |             0 |                0 |            1091 |          2249
(1 row)

set stats_queue_level=on;
SET
create resource queue q with (active_statements = 10);
CREATE QUEUE
create user resqueuetest with resource queue q;
CREATE ROLE
set role resqueuetest;
SET
select 1;
 ?column?
----------
        1
(1 row)

select 1;
 ?column?
----------
        1
(1 row)

select 1;
 ?column?
----------
        1
(1 row)

select * from pg_stat_resqueues;
 queueid | queuename  | n_queries_exec | n_queries_wait | elapsed_exec | elapsed_wait
---------+------------+----------------+----------------+--------------+--------------
    6055 | pg_default |              0 |              0 |            0 |            0
   23344 | q          |              0 |              0 |            0 |            0
(2 rows)

reset role;
RESET
drop role resqueuetest;
DROP ROLE
drop resource queue q;
DROP QUEUE
```

**Comment by kainwen** [comment]
It is a problem that local cache of portal stat of resqueue does not expire after the queue is dropped. I have created a story in MPP's tracker. Will fix this. Thanks.

**Comment by kainwen** [comment]
Another bug test case:

```sql
create resource queue q1 with (active_statements = 10);
create user resqueuetest1 with resource queue q1;
create resource queue q2 with (active_statements = 10);
create user resqueuetest2 with resource queue q2;

set role resqueuetest1;

select 1;
select 1;
select 1;

select * from pg_stat_resqueues;

set role resqueuetest2;

select 1;
select 1;
select 1;

select * from pg_stat_resqueues;

```

**Comment by kainwen** [comment]
Fixed in https://github.com/greenplum-db/gpdb/pull/4590.

**Comment by skahler-pivotal** [comment]
This was still and issue when I tried to readd my patch https://github.com/greenplum-db/gpdb/pull/4625

**Comment by ashwinstar** [comment]
@kainwen do we know final state of this issue, sounds still not full fixed

**Comment by skahler-pivotal** [comment]
@yydzero @kainwen still seeing this

I think I've got https://github.com/greenplum-db/gpdb/pull/5314 wrapped up and ready to go but it fails regress testing on this piece still

**Comment by yydzero** [comment]
+ @gaos1

**Comment by gaos1** [comment]
we will have a look

**Comment by ivannovick** [comment]
closed as can not reproduce

**Comment by liming01** [comment]
Hi @kainwen ,

It seems that the stat info is still not accurate if execute queries without sleep. Below is the reproducible steps:

```
set stats_queue_level=on;

-- start_ignore
drop role resqueuetest;
drop resource queue q;
-- end_ignore

create resource queue q with (active_statements = 10);
create user resqueuetest with resource queue q;

set role resqueuetest;

select 1;
select 1;
select 1;
select pg_sleep(1);

regression=> -- will display q.n_queries_exec=4, and after the query it becomes 5
regression=> select queuename, n_queries_exec from pg_stat_resqueues where queuename = 'q';
 queuename | n_queries_exec
-----------+----------------
 q         |              4
(1 row)

regression=> select queuename, n_queries_exec from pg_stat_resqueues where queuename = 'q';  --here should return 5
 queuename | n_queries_exec
-----------+----------------
 q         |              4
(1 row)

regression=> select pg_sleep(1);
 pg_sleep
----------

(1 row)

regression=> select queuename, n_queries_exec from pg_stat_resqueues where queuename = 'q';
 queuename | n_queries_exec
-----------+----------------
 q         |              7
(1 row)
```
The last third statement should return 5. However, if I put a sleep statement before it, it returns correctly.
