### ISSUE TITLE
Crash: Subquery on external web table scan w/ outer reference

### ISSUE THREAD

**Issue by vraghavan78** [greenplum-db/gpdb#462]
Minimal repro:

*Schema:*
```
CREATE EXTERNAL WEB TABLE webtable (c1 int, c2 int, c3 int) EXECUTE '/Users/vraghavan/Desktop/fake_web.sh' FORMAT 'TEXT' (DELIMITER ',');
```

*Script:*
```
#!/bin/sh

echo "1,2,3"
echo "4,5,6"
```

*Query:*
```
select * from webtable w1 where 10 > (select count(*) from webtable w2 where w2.c2 = w1.c2 group by w2.c2)
Explain:
vraghavan@vraghavan ~/git/gpdb $ psql 
psql (8.3devel)
Type "help" for help.

vraghavan=# explain select * from webtable w1 where 10 > (select count(*) from webtable w2 where w2.c2 = w1.c2 group by w2.c2);
                                         QUERY PLAN                                         
--------------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..13525026000.00 rows=333334 width=12)
   ->  External Scan on webtable w1  (cost=0.00..13525026000.00 rows=111112 width=12)
         Filter: 10 > ((subplan))
         SubPlan 1
           ->  GroupAggregate  (cost=0.00..13525.01 rows=1 width=12)
                 Group By: w2.c2
                 ->  External Scan on webtable w2  (cost=0.00..13500.00 rows=334 width=4)
                       Filter: c2 = $0
 Optimizer status: legacy query optimizer
(9 rows)
```

*Execution: CRASH*
```
vraghavan=# select * from webtable w1 where 10 > (select count(*) from webtable w2 where w2.c2 = w1.c2 group by w2.c2);
ERROR:  Error on receive from seg2 slice1 vraghavan.local:25434 pid=56511: server closed the connection unexpectedly
DETAIL:  
	This probably means the server terminated abnormally
	before or while processing the request.
ERROR:  could not temporarily connect to one or more segments (cdbgang.c:2480)
```

External web table scan does not support rescan. Issue is that we do not add a materialize on top the subplan's materialize node. Any thoughts on this issue are welcome.

**Comment by vitesse-ftian** [comment]
let external web table support rescan?     i don't see any fundamental reason against rescan.

**Comment by atris** [comment]
I believe this has been fixed in Heikki's patch

On Tue, Apr 19, 2016 at 12:00 PM, Feng Tian <notifications@github.com>
wrote:

> let external web table support rescan? i don't see any fundamental reason
> against rescan.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/greenplum-db/gpdb/issues/462#issuecomment-211755789>
>



-- 
Regards,

Atri
*l'apprenant*

**Comment by fengttt** [comment]
Thanks.   I checked master, it is not really fixed, but turned assert into an elog error.   I will wait for the patch, thanks.

**Comment by vraghavan78** [comment]
Fixed.

`
vraghavan=# select * from webtable w1 where 10 > (select count(*) from webtable w2 where w2.c2 = w1.c2 group by w2.c2)                                                                                                                                                                                                                                                    ;
 c1 | c2 | c3
----+----+----
  1 |  2 |  3
  4 |  5 |  6
  1 |  2 |  3
  4 |  5 |  6
  1 |  2 |  3
  4 |  5 |  6
(6 rows)
`
