### ISSUE TITLE
RETURNING Clause not working with INSERT and partitioned table.

### ISSUE THREAD

**Issue by mkiyama** [greenplum-db/gpdb#4735]
### Greenplum version or build
PostgreSQL 9.0beta3 (Greenplum Database 6.0.0-alpha.0+dev.5115.g7339a7420b build commit:7339a7420b9c12930d4c7bbe23af84a4277876b2-
oss) on x86_64-pc-linux-gnu, compiled by GCC gcc (GCC) 6.2.0, 64-bit compiled on Mar 20 2018 18:48:31 (with assert checking)

### OS version and uname -a
Linux centos6-gp5 2.6.32-696.23.1.el6.x86_64 #1 SMP Tue Mar 13 22:44:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Expected behavior
see steps to reproduce the behavior.
### Actual behavior
Insert command should not show (0 rows)

### Step to reproduce the behavior

CREATE TABLE sales (id int, year int, qtr int, day int, region text)
DISTRIBUTED BY (id) 
PARTITION BY RANGE (year) 
( PARTITION yr START (2000) END (2004) EVERY (1) ) ;

insert into sales (id, year, qtr,day,region) values (19, 2002, 3,4, 'asia') returning region ;
 region
--------
(0 rows)

I didn't try other commands that support RETURNING clause.

**Comment by jimmyyih** [comment]
Update and delete seem to work:
```
postgres=# update sales set qtr=4 where qtr=3 returning *;
 id | year | qtr | day | region
----+------+-----+-----+--------
 19 | 2002 |   4 |   4 | asia
(1 row)

UPDATE 1

postgres=# delete from sales returning *;
 id | year | qtr | day | region
----+------+-----+-----+--------
 19 | 2002 |   4 |   4 | asia
(1 row)

DELETE 1
```

Seems like the issue only appears for INSERT on partition tables.

**Comment by mkiyama** [comment]
There seems to be issues with AO/CO tables on my system.

create table t2 (c1 text, c2 int) WITH (appendonly=true, orientation=column) distributed randomly;
These work
insert into t2 values ('bob', 22), ('bill', 23) returning c2;
update t2 set c1 = 'cat' where c2 = 22 returning *;

this returns an error.
delete from t2 where c1 = 'cat' returning * ;

ERROR:  could not open file "base/16384/16405.2" (target block 33554432): No such file or directory  (seg0 slice1 192.168.180.75:40000 pid=7265)

**Comment by yydzero** [comment]
@pivotal-ning-yu @pengzhout for awareness

**Comment by pivotal-ning-yu** [comment]
The plan for `INSERT` is wrong:

```sql
gpadmin=# explain insert into sales (id, year, qtr,day,region) values (19, 2002, 3,4, 'asia') returning region ;
                                 QUERY PLAN
----------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..0.01 rows=1 width=0)
   ->  Insert  (cost=0.00..0.01 rows=1 width=0)
         ->  Result  (cost=0.00..0.01 rows=1 width=0)
 Optimizer: legacy query optimizer
(4 rows)
```

As a contrast the plan for `UPDATE` is like below:

```sql
gpadmin=# explain update sales set qtr=4 where qtr=3 returning *;
                                      QUERY PLAN
--------------------------------------------------------------------------------------
 Gather Motion 3:1  (slice1; segments: 3)  (cost=0.00..2495.00 rows=168 width=54)
   ->  Update  (cost=0.00..2495.00 rows=56 width=54)
         ->  Seq Scan on sales_1_prt_yr_1 sales  (cost=0.00..623.75 rows=14 width=54)
               Filter: qtr = 3
         ->  Seq Scan on sales_1_prt_yr_2 sales  (cost=0.00..623.75 rows=14 width=54)
               Filter: qtr = 3
         ->  Seq Scan on sales_1_prt_yr_3 sales  (cost=0.00..623.75 rows=14 width=54)
               Filter: qtr = 3
         ->  Seq Scan on sales_1_prt_yr_4 sales  (cost=0.00..623.75 rows=14 width=54)
               Filter: qtr = 3
 Optimizer: legacy query optimizer
(11 rows)
```

**Comment by pivotal-ning-yu** [comment]
Please ignore my previous comment, the plan is not wrong. I checked on segment, on `INSERT` command `resultRelInfo->ri_projectReturning` is NULL in `ExecInsert()`, need to find out why.

**Comment by pivotal-ning-yu** [comment]
In `subquery_planner()`:

```C
    /*
     * Do the main planning.  If we have an inherited target relation, that
     * needs special processing, else go straight to grouping_planner.
     */
    if (parse->resultRelation &&
        rt_fetch(parse->resultRelation, parse->rtable)->inh)
        plan = inheritance_planner(root);
    else
    {
        plan = grouping_planner(root, tuple_fraction);
```

For `UPDATE` the `inh` mark is true so it makes a plan for the case "where the result relation is an inheritance set", it will append all the partitions to the `returningLists`, however for `INSERT` the `inh` mark is false, so the `returningLists` only contains the parent table, which cause `ri_projectReturning` to be NULL in `ExecInsert()` on segment so no tuple is returned.

**Comment by hlinnaka** [comment]
Fixed. Thanks for the report, @mkiyama!

**Comment by asimrp** [comment]
Part of this issue, pertaining to Mel's delete with returning query on AO tables, is not fixed yet:
```SQL
create table t2 (c1 text, c2 int) WITH (appendonly=true, orientation=column) distributed randomly;
insert into t2 values ('bob', 22), ('bill', 23) returning c2;
update t2 set c1 = 'cat' where c2 = 22 returning *;
delete from t2 where c1 = 'cat' returning * ;
ERROR:  could not open file "base/12515/16390.2" (target block 33554432): No such file or directory  (seg1 slice1 127.0.1.1:25433 pid=8457)
```
The fix should be addressed as part of this fixme in `ExecDelete()`: `        // GPDB_91_MERGE_FIXME: What if it's an AO table?`                                                                                                                                                                                                               

This can be tracked as a separate issue but let me reopen this for now.

**Comment by hlinnaka** [comment]
Ah, good point, I glanced over that second issue.

I opened a separate issue, #5489, to track that.
